version: "3.8"

networks:
  piggy_network:
    name: piggy_network

services:

  piggy_base:
    container_name: piggy_base
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: piggy
    networks:
      - piggy_network

  piggy:
    container_name: piggy
    image: vo13crabs/piggy:1.9.1
    environment:
      BASE_URL: jdbc:postgresql://piggy_base:5432/postgres
      POSTGRES_PASSWORD: piggy
    networks:
      - piggy_network
    ports:
      - 8090:8080
