version: "3.8"

networks:
  piggy_network:
    name: piggy_network

services:

  piggy_base:
    container_name: piggy_base
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: piggy
    networks:
      - piggy_network

  piggy:
    container_name: piggy
    build:
      context: .
      dockerfile: Dockerfile
    command: java -Dcom.sun.management.jmxremote -Xmx128m -jar free_bank.jar
    environment:
      BASE_URL: jdbc:postgresql://piggy_base:5432/postgres
      POSTGRES_PASSWORD: piggy
    networks:
      - piggy_network
    ports:
      - 8090:8080
